/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_faustgames_forest_NativeInterface */

#ifndef _Included_com_faustgames_forest_NativeInterface
#define _Included_com_faustgames_forest_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_faustgames_forest_NativeInterface
 * Method:    initAssetManager
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT void JNICALL Java_com_faustgames_forest_NativeInterface_initAssetManager
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_faustgames_forest_NativeInterface
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_faustgames_forest_NativeInterface_onSurfaceCreated
  (JNIEnv *, jobject);

/*
 * Class:     com_faustgames_forest_NativeInterface
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_faustgames_forest_NativeInterface_onSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_faustgames_forest_NativeInterface
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_faustgames_forest_NativeInterface_onDrawFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
